---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    labels: ["go", "dependencies"]
    groups:
      dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    labels: ["github_actions", "dependencies"]
    groups:
      dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
