---
title: Privateer CLI
metadata:
  id: PrivProj.CLI
  description: Threat catalog for Privateer CLI
  version: 2026.Feb.28
  author:
    id: pvtr-maintainers
    name: Privateer Maintainer Group
    type: Human
  mapping-references:
    - id: CCC
      title: Common Cloud Controls Core
      version: v2025.10
      url: https://github.com/finos/common-cloud-controls/releases/download/v2025.10/CCC.Core_v2025.10.yaml
      description: |
        Foundational repository of reusable security controls, capabilities,
        and threat models maintained by FINOS.

imported-capabilities:
  - reference-id: CCC
    entries:
      - id: CCC.Core.CP10
        remarks: Log Publication (Privateer doesn't send logs, but does write to io and file)
      - id: CCC.Core.CP28
        remarks: Command-line Interface

imported-threats:
  - reference-id: CCC
    entries:
      - id: CCC.Core.TH07
        remarks: Logs are Tampered With or Deleted
      - id: CCC.Core.TH16
        remarks: Publications are Disabled

capabilities:
  - id: PrivProj.CLI.CP01
    title: User Configuration Ingestion
    description: |
      Accepts CLI inputs and reads user-provided YAML configuration files to determine
      runtime behavior for the core CLI and selected plugins
  - id: PrivProj.CLI.CP02
    title: Multi-plugin Variable Handling
    description: Manages configuration variables and secrets for all plugins that are executed
  - id: PrivProj.CLI.CP03
    title: Plugin Enumeration
    description: |
      Detects plugins available on the local filesystem by searching a well-known
      or user-defined location
  - id: PrivProj.CLI.CP04
    title: Plugin Execution
    description: |
      Executes one or more plugins as independent sub-processes and directs output
      to the terminal or filesystem
  - id: PrivProj.CLI.CP05
    title: Plugin Generation
    description: |
      Automates the generation of plugin scaffolding from Gemara Control Catalogs
      using the `generate-plugin` command
  - id: PrivProj.CLI.CP06
    title: Configurable Log Output
    description: Allows users to adjust the verbosity and location of log outputs
  - id: PrivProj.CLI.CP07
    title: Configurable Result Output
    description: Allows users to configure the output location for runtime execution results

threats:
  - id: PrivProj.CLI.TH01
    title: Plugin Binary Hijacking
    description: |
      Privateer discovers plugins in local directories. If an attacker gains write access to
      the plugin path, they can place a malicious binary that Privateer will execute.
      This may be used to feed inaccurate data into the victim's security scans,
      and/or compromise the target resource.
    capabilities:
      - reference-id: PrivProj.CLI
        entries:
          - reference-id: PrivProj.CLI.CP03
          - reference-id: PrivProj.CLI.CP04
  - id: PrivProj.CLI.TH02
    title: Config Secrets are Unintentionally Accessed by a Different Plugin
    description: |
      Privateer manages all variables, including secrets, in the same process. If users are running
      multiple plugins from different authors or contexts, sensitive variables intended for one
      context may become accessible to another plugin executed in the same run.
    capabilities:
      - reference-id: PrivProj.CLI
        entries:
          - reference-id: PrivProj.CLI.CP01
          - reference-id: PrivProj.CLI.CP02
  - id: PrivProj.CLI.TH03
    title: Sensitive Data Exposure via Insecure Configuration Permissions
    description: |
      Configuration files containing resource identifiers or sensitive metadata are stored on
      the local filesystem. In shared or improperly isolated environments, insecure file
      permissions can lead to the unauthorized exposure of these artifacts.
    capabilities:
      - reference-id: PrivProj.CLI
        entries:
          - reference-id: PrivProj.CLI.CP01
          - reference-id: PrivProj.CLI.CP07
  - id: PrivProj.CLI.TH04
    title: Unintentional Plugin Enumeration
    description: |
      If an attacker gains the ability to run Privateer CLI, even in a sandbox or ephemeral environment,
      and even without access to configuration data, they may be able to infer the contents of the
      victim's production environment by enumerating Privateer plugins.
  - id: PrivProj.CLI.TH05
    title: Insecure Defaults in Generated Scaffolding
    description: |
      If the templates used by the `generate-plugin` command contain insecure default settings or
      vulnerable boilerplate, all new plugins generated by the CLI will inherit these flaws,
      scaling the vulnerability across the ecosystem.
    capabilities:
      - reference-id: PrivProj.CLI
        entries:
          - reference-id: PrivProj.CLI.CP05
  - id: PrivProj.SDK.TH06
    title: Scaffolding Template Poisoning
    description: |
      Compromise of the `plugin-generator-templates` allows an attacker to inject malicious code or
      dependencies into the wireframes used by `generate-plugin`, tainting all new service packs at
      the time of creation.
    capabilities:
      - reference-id: PrivProj.SDK
        entries:
          - reference-id: PrivProj.CLI.CP05
