logLevel: Debug
write-directory: test_output
write: true
output: yaml
services:
  my-service-0:
    plugin: abs
  my-service-1:
    plugin: dev
    loglevel: Debug
    test-suites:
      # - tlp_red
      # - tlp_amber
      - tlp_green
      - tlp_clear
    vars:
      key: value
