# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privateer < Formula
  desc ""
  homepage "https://github.com/privateerproj/privateer"
  version "0.0.0"

  on_macos do
    url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Darwin_all.tar.gz"
    sha256 "2710300ce20f8dec4f61eb1634aa2b05318443980a9a8832a08316fa36bef076"

    def install
      bin.install "privateer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Linux_arm64.tar.gz"
      sha256 "fd8c0f1effd1c66b26d54c51dae2ec2291bf8de85c2ef32d26951484df808e4b"

      def install
        bin.install "privateer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Linux_x86_64.tar.gz"
      sha256 "f9136f748a6bb507df1a5b5351f6c0c5ff28012f7fee4f781998a272c7dd12a2"

      def install
        bin.install "privateer"
      end
    end
  end
end
