blank_issues_enabled: true

contact_links:
  - name: Ask a question by filing an issue
    url: https://github.com/privateerproj/privateer/issues/new/choose
    about: Ask a question by filing an issue
