issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:privateerproj/privateer:(pull_request|ref:refs/heads/.+)"
claim_pattern:
  job_workflow_ref: "^privateerproj/privateer/.github/workflows/(ci|osps-security-assessment)\\.yml@refs/(heads/.+|pull/[0-9]+/merge)$"

permissions:
  contents: read
  statuses: read
  deployments: read
  security_events: read
  administration: read
