issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:privateerproj/privateer:(pull_request|ref:refs/heads/main)"
claim_pattern:
  job_workflow_ref: "^privateerproj/privateer/.github/workflows/ci.yml@refs/(heads/main|pull/[0-9]+/merge)$"

permissions:
  contents: read
