---
name: "Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  auto_labeler:
    permissions:
      contents: write
      pull-requests: write
    uses: jmeridth/reusable-workflows/.github/workflows/auto-labeler.yaml@d989a3cdb0cfd84f294dd3016165114b85d202c7
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
