---
name: "Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request_target' }}

jobs:
  auto_labeler:
    permissions:
      contents: read         # Read repository contents for the reusable workflow
      pull-requests: write   # Apply labels to the pull request
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@5193129233b450e9174d4d92fcc467919a989882
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
