---
name: "Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  auto_labeler:
    permissions:
      contents: write
      pull-requests: write
    uses: jmeridth/reusable-workflows/.github/workflows/auto-labeler.yaml@53a9c808122ffaae9af948f72139fb4bd44ab74c
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
