---
name: "Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  auto_labeler:
    permissions:
      contents: read
      pull-requests: write
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@30db3296210fe74bc1214e5710f8db5ac6d3a1ad
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
