## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
jobs:
  lint_pr_title:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/pr-title.yaml@30db3296210fe74bc1214e5710f8db5ac6d3a1ad
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
